### ISSUE TITLE
routes: analytics as first class citizen

### ISSUE THREAD

**Issue by sballesteros** [sballesteros/linked-data-registry#3]
How about changing

GET /:dpkgname/:version/:resourcename/

to 

GET /:dpkgname/:version/**dataset**/:datasetname/

so that we can have

GET /:dpkgname/:version/**analytics**/**:analyticsname**/

Pros: analytics and dataset can now potentially have the same name
Cons: longer URLs when we link (inputs / outputs ...)

**Comment by JDureau** [comment]
Works for me!
