### ISSUE TITLE
citation without url => {"error":"publish aborted obj is undefined" code 403}

### ISSUE THREAD

**Issue by JDureau** [sballesteros/linked-data-registry#8]
I've modified package-jsonld so that it supports citations without urls, but the registry still refuses such packages, with the following error: 

{"error":"publish aborted obj is undefined" code 403}

After digging a little, it appears that this error is thrown [here](https://github.com/standard-analytics/linked-data-registry/blob/master/proxy/app.js#L718). Haven't yet understood why couch would forbid this operation. If you have any suggestion.

**Comment by sballesteros** [comment]
Have you redone npm run push

**Comment by sballesteros** [comment]
Also the module ldstars (and package-dna) also relies on citation having an URL. The registry computes the rating so that might be it.

**Comment by JDureau** [comment]
I'm playing with an ec2 instance, npm run push doesn't work on there:

ubuntu@domU-12-31-39-04-6E-95:~/linked-data-registry$ sudo npm run push

> linked-data-registry@0.5.0 push /home/ubuntu/linked-data-registry
> (cd registry && NODE_HOST=localhost NODE_PORT=3000 NODE_PORT_HTTPS=4000 REGISTRY_DB_NAME=registry INTERACTION_DB_NAME=interaction ../node_modules/.bin/couchapp push app.js http://seb:seb@127.0.0.1:5984/registry) && (cd owners && ../node_modules/.bin/couchapp push app.js http://seb:seb@127.0.0.1:5984/_users)

Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete](net.js:895:19)

npm ERR! linked-data-registry@0.5.0 push: `(cd registry && NODE_HOST=localhost NODE_PORT=3000 NODE_PORT_HTTPS=4000 REGISTRY_DB_NAME=registry INTERACTION_DB_NAME=interaction ../node_modules/.bin/couchapp push app.js http://seb:seb@127.0.0.1:5984/registry) && (cd owners && ../node_modules/.bin/couchapp push app.js http://seb:seb@127.0.0.1:5984/_users)`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the linked-data-registry@0.5.0 push script.
npm ERR! This is most likely a problem with the linked-data-registry package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (cd registry && NODE_HOST=localhost NODE_PORT=3000 NODE_PORT_HTTPS=4000 REGISTRY_DB_NAME=registry INTERACTION_DB_NAME=interaction ../node_modules/.bin/couchapp push app.js http://seb:seb@127.0.0.1:5984/registry) && (cd owners && ../node_modules/.bin/couchapp push app.js http://seb:seb@127.0.0.1:5984/_users)
npm ERR! You can get their info via:
npm ERR!     npm owner ls linked-data-registry
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.11.0-15-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "run" "push"
npm ERR! cwd /home/ubuntu/linked-data-registry
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/linked-data-registry/npm-debug.log
npm ERR! not ok code 0

**Comment by JDureau** [comment]
I've checked the ldstars module, it does not impose having a url:

https://github.com/standard-analytics/ldstars/blob/master/index.js#L157

**Comment by sballesteros** [comment]
you can run `npm run push` from any machine have all the source code of the linked-data-registry. Just setup all the env variable so that they point to where the proxy is running and where the DB are hosted.
e.g.

```
NODE_HOST=registry.standardanalytics.io NODE_PORT=80 NODE_PORT_HTTPS=443 REGISTRY_DB_NAME=registry INTERACTION_DB_NAME=interaction ../node_modules/.bin/couchapp push app.js $COUCH/registry 
```

where $COUCH contains you admin credential for CouchDb.

PS: If you post log be careful not include passwords.
